openapi: 3.0.0
servers:
  - url: //petstore.swagger.io/v2
    description: Default server
  - url: //petstore.swagger.io/sandbox
    description: Sandbox server
info:
  description: |
    This is a sample server Petstore server.
    You can find out more about Swagger at
    [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
    For this sample, you can use the api key `special-key` to test the authorization filters.

    # Introduction
    This API is documented in **OpenAPI format** and is based on
    [Petstore sample](http://petstore.swagger.io/) provided by [swagger.io](http://swagger.io) team.
    It was **extended** to illustrate features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
    tool and [ReDoc](https://github.com/Redocly/redoc) documentation. In addition to standard
    OpenAPI syntax we use a few [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md).

    # OpenAPI Specification
    This API is documented in **OpenAPI format** and is based on
    [Petstore sample](http://petstore.swagger.io/) provided by [swagger.io](http://swagger.io) team.
    It was **extended** to illustrate features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
    tool and [ReDoc](https://github.com/Redocly/redoc) documentation. In addition to standard
    OpenAPI syntax we use a few [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md).

    # Cross-Origin Resource Sharing
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).
    And that allows cross-domain communication from the browser.
    All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    # Authentication

    Petstore offers two forms of authentication:
      - API Key
      - OAuth2
    OAuth2 - an open protocol to allow secure authorization in a simple
    and standard method from web, mobile and desktop applications.

    <SecurityDefinitions />

  version: 1.0.0
  title: Filing API
  description: 'This is the API for receiving filings concerning citizens taxable transactions, from sharing economy platforms, for project DEL (Deleøkonomi)"
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    email: apiteam@swagger.io
  x-logo:
    url: 'https://eu.eu-supply.com/img/brandings/skatteministeriet.JPG'
    altText: Skatteministeriet Logo
    href: ''
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
  - name: pet_model
    x-displayName: The Pet Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Pet" />
  - name: store_model
    x-displayName: The Order Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Order" exampleRef="#/components/examples/Order" showReadOnly={true} showWriteOnly={true} />
x-tagGroups:
  - name: General
    tags:
      - pet
      - store
  - name: User Management
    tags:
      - user
  - name: Models
    tags:
      - pet_model
      - store_model
paths:
  # ------------- FilingController -------------
  /platforms/{platformId}/{assetType}-filing/{filingReference}:
    post:
      tags:
        - filings
      parameters:
        - $ref: '#/components/parameters/platformId'
        - $ref: '#/components/parameters/assetType'
        - $ref: '#/components/parameters/filingReference'
      summary: Add or update a filing regarding a danish taxpayers sharing economy transactions through a sharing economy platform
      operationId: addFiling
      requestBody:
        description: Data representing a danish taxpayers transactions through a sharing economy platform
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Filing'
        required: true
      responses:
        201:
          description: A correct filing was submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulFiling'
        400:
          description: Wrong sequenceNumber or wrong platformId was supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilingError'
        503:
          description: Unknown token was supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilingError'
    get:
      tags:
        - filings
      parameters:
        - $ref: '#/components/parameters/platformId'
        - $ref: '#/components/parameters/assetType'
        - $ref: '#/components/parameters/filingReference'
      summary: Show a filing from a platform of a specific assetType with the given filingReference and sequenceNumber
      operationId: showFilingWithReference
      responses:
        200:
          description: Returns a list of filings reported by the platform.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShortFiling'
                  links:
                    $ref: '#/components/schemas/UnversionedLink'

  /platforms/{platformId}/{assetType}-filing:
    get:
      tags:
        - filings
      parameters:
        - $ref: '#/components/parameters/platformId'
        - $ref: '#/components/parameters/assetType'
      summary: List all filings from a platform of a specific assetType
      operationId: listFilings
      responses:
        200:
          description: Returns a list of filings reported by the platform.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShortFiling'
                  links:
                    $ref: '#/components/schemas/UnversionedLink'

  /platforms/{platformId}/{assetType}-filing/{filingReference}/{sequenceNumber}:
    get:
      tags:
        - filings
      parameters:
        - $ref: '#/components/parameters/platformId'
        - $ref: '#/components/parameters/assetType'
        - $ref: '#/components/parameters/filingReference'
        - $ref: '#/components/parameters/sequenceNumber'
      summary: Show a filing from a platform of a specific assetType with the given filingReference and sequenceNumber
      operationId: showFilingWithSequence
      responses:
        200:
          description: Returns a list of filings reported by the platform.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShortFiling'
                  links:
                    $ref: '#/components/schemas/UnversionedLink'

  /platforms/{platformId}/{assetType}-filing/{filingReference}/versions:
    get:
      tags:
        - filings
      parameters:
        - $ref: '#/components/parameters/platformId'
        - $ref: '#/components/parameters/assetType'
        - $ref: '#/components/parameters/filingReference'
      summary: Show all filings and updates from a platform of a specific assetType with the given filingReference
      operationId: listFilingsWithReference
      responses:
        200:
          description: Returns a list of filings reported by the platform.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShortFiling'
                  links:
                    $ref: '#/components/schemas/UnversionedLink'

components:
  # ------------- Path Parameters -------------
  parameters:
    platformId:
      in: path
      name: platformId
      required: true
      schema:
        type: string
      description: uuid of the platform that is sending the request
      example: "b410b282-168e-4ebe-805a-e73df079769d"
    assetType:
      in: path
      name: assetType
      schema:
        type: string
      required: true
      description: The assets type, one of the three following values - accommodation, vehicle, boat
      example: "accommodation"
    filingReference:
      in: path
      name: filingReference
      schema:
        type: string
      required: true
      description: The 3rd party platforms identifier for a platform
      example: "2a0f1f82-8ebf-418f-bbd8-b018f33a6971"
    sequenceNumber:
      in: path
      name: sequenceNumber
      schema:
        type: string
      required: true
      description: The 3rd party platforms identifier for a platform
      example: "0"
  # ------------- Schemas -------------
  schemas:
    # ------------- 2xx -------------
    SuccessfulFiling:
      required:
        - data
        - links
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
            - links
        links:
          type: object
          required:
            - self
          properties:
            self:
              type: string
              example: "/platforms/85232389-c876-40a4-9b67-f95eec44825d/accommodation-filings/123456"
    # ------------- 4xx -------------
    FilingError:
      required:
        - errors
      type: object
      properties:
        error:
          type: object
          required:
            - title
            - source
            - detail
          properties:
            title:
              type: string
              example: "Wrong sequenceNumber"
            source:
              type: object
              required:
                - pointer
              properties:
                pointer:
                  type: string
                  example: "#/data/attributes/sequenceNumber"
            detail:
              type: string
              example: "The value for sequenceNumber was 1 in the payload, but 2 was expected"
    # ------------- 5xx -------------

    # ------------- Reusable entities -------------
    Filing:
      required:
        - data
      type: object
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              example: "accomodation-filing"
            attributes:
              type: object
              required:
                - sequenceNumber
                - filingData
              properties:
                sequenceNumber:
                  type: integer
                  example: 0
                filingData:
                  type: object
                  required:
                    - personIdToken
                    - amount
                    - currency
                    - startTimestamp
                    - endTimestamp
                    - paymentTimestamp
                    - asset
                  properties:
                    personIdToken:
                      type: string
                      example: "46970070-0aa2-4d4c-bad9-aa18a248d5cb"
                    amount:
                      type: integer
                      example: 795.51
                    currency:
                      type: string
                      example: "DKK"
                    startTimestamp:
                      type: string
                      format: date-time
                    endTimestamp:
                      type: string
                      format: date-time
                    paymentTimestamp:
                      type: string
                      format: date-time
                    asset:
                      type: object
                      properties:
                        assetUniqueId:
                          type: string
                          example: ""
                        assetCountryCode:
                          type: string
                          example: "DK"
                        level1:
                          type: string
                          example: ""
                        level2:
                          type: string
                          example: ""
                        level3:
                          type: string
                          example: ""
                        level4:
                          type: string
                          example: ""
                        unstructuredAddress:
                          type: object
                          properties:
                            countryCode:
                              type: string
                              example: ""
                            addressLine1:
                              type: string
                              example: ""
                            addressLine2:
                              type: string
                              example: ""
                            addressLine3:
                              type: string
                              example: ""
                            addressLine4:
                              type: string
                              example: ""
    ShortFiling:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        type:
          type: string
          example: "accommodation-filing"
        attributes:
          type: object
          required:
            - filingReference
            - sequenceNumber
            - platformId
            - filingData
          properties:
            filingReference:
              type: string
              example: "12345"
            sequenceNumber:
              type: string
              example: "0"
            platformId:
              type: string
              example: "85232389-c876-40a4-9b67-f95eec44825d"
            filingData:
              type: object
              required:
                - amount
                - currency
                - startTimestamp
                - endTimestamp
                - paymentTimestamp
              properties:
                amount:
                  type: number
                  example: 1234.0
                currency:
                  type: string
                  example: "DKK"
                startTimestamp:
                  type: string
                  example: "2019-03-12T12:41:10.218Z"
                endTimestamp:
                  type: string
                  example: "2019-03-12T12:41:10.218Z"
                paymentTimestamp:
                  type: string
                  example: "2019-03-12T12:41:10.218Z"
        links:
          $ref: '#/components/schemas/VersionedLink'

    VersionedLink:
      required:
        - self
      type: object
      properties:
        self:
          type: string
          example: "/platforms/85232389-c876-40a4-9b67-f95eec44825d/accommodation-filings/12345/versions/0"
    UnversionedLink:
      required:
        - self
      type: object
      properties:
        self:
          type: string
          example: "/platforms/85232389-c876-40a4-9b67-f95eec44825d/accommodation-filings"
#  securitySchemes:
#    api_key:
#      type: apiKey
#      in: header
#      name: X-API-KEY
